server:
  port: 8001

#thymeleaf start
spring:
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    # 开发时关闭缓存,不然没法看到实时页面
    cache: false
#thymeleaf end

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: org.coastline.common.web.dao
  configuration:
    # 下划线转驼峰
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
